import { createElement } from 'lwc';
import Cgi_LWC004_GestionAcquisitions from 'c/cgi_LWC004_GestionAcquisitions';

describe('c-cgi-l-w-c-004-gestion-acquisitions', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-cgi-l-w-c-004-gestion-acquisitions', {
            is: Cgi_LWC004_GestionAcquisitions
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});